gui:
  promptToReturnFromSubprocess: false
  theme:
    selectedLineBgColor:
      - '#3d4f6b'
    selectedRangeBgColor:
      - '#3d4f6b'
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
os:
  edit: "$HOME/bin/nvim-open {{filename}}"
  editAtLine: "$HOME/bin/nvim-open +{{line}} {{filename}}"
